"""DiffAnalyzer 单元测试 - 语言检测、Chunk 拆分、过滤。"""

import pytest
from app.core.diff_analyzer import DiffAnalyzer, DiffChunk


@pytest.fixture
def analyzer():
    return DiffAnalyzer(max_chunk_tokens=8000)


# ─────────────────────────────────────────────
# detect_languages
# ─────────────────────────────────────────────

class TestDetectLanguages:
    def test_go_files(self, analyzer, sample_diff_go):
        langs = analyzer.detect_languages(sample_diff_go)
        assert langs == ["go"]

    def test_python_files(self, analyzer, sample_diff_python):
        langs = analyzer.detect_languages(sample_diff_python)
        assert langs == ["python"]

    def test_multi_language(self, analyzer, sample_diff_multi):
        langs = analyzer.detect_languages(sample_diff_multi)
        assert set(langs) == {"go", "python"}

    def test_empty_diff(self, analyzer):
        assert analyzer.detect_languages("") == []

    def test_auto_generated_filtered(self, analyzer):
        diff = "diff --git a/package-lock.json b/package-lock.json\n--- a/package-lock.json\n+++ b/package-lock.json\n@@ -1 +1 @@\n-old\n+new"
        assert analyzer.detect_languages(diff) == []

    def test_unknown_extension(self, analyzer):
        diff = "diff --git a/data.xyz b/data.xyz\n--- a/data.xyz\n+++ b/data.xyz\n@@ -1 +1 @@\n-old\n+new"
        assert analyzer.detect_languages(diff) == []


# ─────────────────────────────────────────────
# chunk_diff
# ─────────────────────────────────────────────

class TestChunkDiff:
    def test_single_chunk(self, analyzer, sample_diff_go):
        chunks = analyzer.chunk_diff(sample_diff_go)
        assert len(chunks) >= 1
        assert all(isinstance(c, DiffChunk) for c in chunks)
        assert chunks[0].language == "go"

    def test_chunk_ids_are_unique(self, analyzer, sample_diff_multi):
        chunks = analyzer.chunk_diff(sample_diff_multi)
        ids = [c.chunk_id for c in chunks]
        assert len(ids) == len(set(ids))

    def test_empty_diff(self, analyzer):
        assert analyzer.chunk_diff("") == []

    def test_chunk_content_not_empty(self, analyzer, sample_diff_go):
        chunks = analyzer.chunk_diff(sample_diff_go)
        for c in chunks:
            assert len(c.content) > 0

    def test_token_limit_respected(self):
        """验证大 diff 会被切分为多个 chunk。"""
        small_analyzer = DiffAnalyzer(max_chunk_tokens=50)
        # 构建一个大 diff
        big_diff = "diff --git a/big.go b/big.go\n"
        for i in range(100):
            big_diff += f"+// line {i}: {'x' * 50}\n"
        chunks = small_analyzer.chunk_diff(big_diff)
        assert len(chunks) > 1


# ─────────────────────────────────────────────
# _estimate_tokens
# ─────────────────────────────────────────────

class TestEstimateTokens:
    def test_ascii_text(self, analyzer):
        # 100 ASCII chars ≈ 25 tokens (100/4)
        tokens = analyzer._estimate_tokens("a" * 100)
        assert 20 <= tokens <= 30

    def test_cjk_text(self, analyzer):
        # 100 CJK chars ≈ 67 tokens (100/1.5)
        tokens = analyzer._estimate_tokens("你" * 100)
        assert 60 <= tokens <= 75

    def test_empty_text(self, analyzer):
        assert analyzer._estimate_tokens("") == 0


# ─────────────────────────────────────────────
# _split_by_file
# ─────────────────────────────────────────────

class TestSplitByFile:
    def test_splits_correctly(self, analyzer, sample_diff_multi):
        parts = analyzer._split_by_file(sample_diff_multi)
        assert len(parts) == 2
        paths = [p[0] for p in parts]
        assert "src/main.py" in paths
        assert "lib/utils.go" in paths

    def test_single_file(self, analyzer, sample_diff_go):
        parts = analyzer._split_by_file(sample_diff_go)
        assert len(parts) == 2  # 两个文件


# ─────────────────────────────────────────────
# _is_auto_generated
# ─────────────────────────────────────────────

class TestIsAutoGenerated:
    def test_lock_files(self, analyzer):
        assert analyzer._is_auto_generated("package-lock.json")
        assert analyzer._is_auto_generated("go.sum")
        assert analyzer._is_auto_generated("yarn.lock")

    def test_vendor_dirs(self, analyzer):
        assert analyzer._is_auto_generated("vendor/github.com/foo/bar.go")
        assert analyzer._is_auto_generated("node_modules/lodash/index.js")

    def test_normal_files(self, analyzer):
        assert not analyzer._is_auto_generated("src/main.py")
        assert not analyzer._is_auto_generated("cmd/server/main.go")
